### ISSUE TITLE
about the idt_tools' url

### ISSUE THREAD

**Issue by davendw49** [ggirelli/bcsuite#1]
Since the website has changed it's xml/html construction, how should I change the source code of idt_tool if i only wanna use the tools on [idtdna](https://sg.idtdna.com/calc/analyzer)?
![image](https://user-images.githubusercontent.com/32675226/73593038-ee7fe400-453a-11ea-80b1-d4d6536e24e9.png)
thanks!

**Comment by ggirelli** [comment]
Hi @davendw49, and sorry for the late reply. I just had a look at their new XML output ([example](http://www.idtdna.com/AnalyzerService/AnalyzerService.asmx/SelfDimer)]) and they indeed changed it! Originally the DimerInfo tag only contained the DeltaG value, which now they nest in a sub-tag called DeltaG instead.

What you would need to do to recover the original behavior is to change this line:
```min(as.numeric(seqdata$DimerInfo)```
You need to collect all the DeltaG values first and then return the lowest (`min`) one.

I do not update this repository anymore (soon to be archived) as I implemented this alternative package instead: [oligo-melting](https://github.com/ggirelli/oligo-melting). In the coming weeks, I will also release an updated version of it.

I hope this helps! If you fix it, it would be great if you could share it here or make a pull request! I will close the thread for the moment but feel free to reply with any inquiries you might have on the matter.

Cheers, G
